[job]
dump_folder = "./outputs"
description = "Flux-schnell model"
print_config = true
custom_config_module = "torchtitan.experiments.flux.job_config"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 100
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "flux"
flavor = "flux-schnell"

[optimizer]
name = "AdamW"
lr = 1e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 3_000
decay_ratio = 0.0

[training]
local_batch_size = 32
max_norm = 1.0
steps = 30_000
dataset = "cc12m-wds"
classifier_free_guidance_prob = 0.447
img_size = 256

[encoder]
t5_encoder = "google/t5-v1_1-xxl"
clip_encoder = "openai/clip-vit-large-patch14"
max_t5_encoding_len = 256
autoencoder_path = "torchtitan/experiments/flux/assets/autoencoder/ae.safetensors"

[validation]
enable = true
dataset = "coco-validation"
local_batch_size = 32
steps = 6
freq = 1000
enable_classifier_free_guidance = true
classifier_free_guidance_scale = 5.0
denoising_steps = 50
save_img_folder = "img"
save_img_count = 1
all_timesteps = false

[parallelism]
data_parallel_replicate_degree = 2
data_parallel_shard_degree = 8
[activation_checkpoint]
mode = "full"

[checkpoint]
enable = true
folder = "checkpoints"
interval = 1_000
last_save_model_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]
